import { useEffect, useRef } from 'react'
import { useReducedMotion } from './motion'

/* ============================================================================
   Canvas dotted background that shimmers.

   Ported from the supplied TSX component. Four changes were needed for this
   codebase, each for a reason:

   1. JavaScript, no "use client". This is Vite + React, not Next, and the
      project is plain JS — the type annotations would not parse.

   2. prefers-reduced-motion draws ONE static frame and never starts the loop.
      The original animates unconditionally; a permanently shimmering field is
      exactly what that setting exists to switch off, and every other animation
      on this site already honours it.

   3. The light/dark colour pairs are collapsed to a single pair. This site has
      one theme, so resolving a dark variant meant a MutationObserver on
      <html> watching for a class that never changes. The CSS-variable lookup
      is kept, because the palette lives in variables.

   4. clearRect is in CSS pixels. After setTransform(dpr,…) the context is
      already scaled, so clearing to canvas.width cleared a dpr-times-too-large
      rect; and the dot grid is now regenerated by the ResizeObserver rather
      than only on window resize, so a container that changes size without the
      window changing no longer leaves a band of missing dots.
   ========================================================================== */

function readVar(el, name) {
  if (!name) return null
  const key = name.startsWith('--') ? name : `--${name}`
  const local = getComputedStyle(el).getPropertyValue(key).trim()
  if (local) return local
  return getComputedStyle(document.documentElement).getPropertyValue(key).trim() || null
}

export default function DottedGlow({
  className = '',
  style,
  gap = 14,
  radius = 5.5,
  color = 'rgba(255,255,255,0.7)',
  glowColor = 'rgba(198,154,69,0.9)',
  colorVar,
  glowColorVar,
  opacity = 0.8,
  backgroundOpacity = 0,
  speedMin = 0.3,
  speedMax = 1.4,
  speedScale = 1,
}) {
  const canvasRef = useRef(null)
  const wrapRef = useRef(null)
  const reduce = useReducedMotion()

  useEffect(() => {
    const canvas = canvasRef.current
    const wrap = wrapRef.current
    if (!canvas || !wrap) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const dotColor = readVar(wrap, colorVar) || color
    const dotGlow = readVar(wrap, glowColorVar) || glowColor
    const dpr = Math.min(Math.max(1, window.devicePixelRatio || 1), 2)

    let dots = []
    let raf = 0
    let stopped = false
    let visible = true

    const size = () => wrap.getBoundingClientRect()

    const resize = () => {
      const { width, height } = size()
      canvas.width = Math.max(1, Math.floor(width * dpr))
      canvas.height = Math.max(1, Math.floor(height * dpr))
      canvas.style.width = `${Math.floor(width)}px`
      canvas.style.height = `${Math.floor(height)}px`
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
    }

    const build = () => {
      const { width, height } = size()
      const cols = Math.ceil(width / gap) + 2
      const rows = Math.ceil(height / gap) + 2
      const min = Math.min(speedMin, speedMax)
      const span = Math.max(Math.max(speedMin, speedMax) - min, 0)
      dots = []
      for (let i = -1; i < cols; i++) {
        for (let j = -1; j < rows; j++) {
          dots.push({
            // every other row is offset half a step, so the field reads as a
            // scatter rather than a hard square grid
            x: i * gap + (j % 2 === 0 ? 0 : gap * 0.5),
            y: j * gap,
            phase: Math.random() * Math.PI * 2,
            speed: min + Math.random() * span,
          })
        }
      }
    }

    const paint = (time) => {
      const { width, height } = size()
      ctx.clearRect(0, 0, width, height)
      ctx.globalAlpha = opacity

      if (backgroundOpacity > 0) {
        const g = ctx.createRadialGradient(
          width * 0.5, height * 0.4, Math.min(width, height) * 0.1,
          width * 0.5, height * 0.5, Math.max(width, height) * 0.7,
        )
        g.addColorStop(0, 'rgba(0,0,0,0)')
        g.addColorStop(1, `rgba(0,0,0,${Math.min(Math.max(backgroundOpacity, 0), 1)})`)
        ctx.fillStyle = g
        ctx.fillRect(0, 0, width, height)
      }

      ctx.save()
      ctx.fillStyle = dotColor
      for (const d of dots) {
        // triangle wave 0..1..0, so brightening and dimming take equal time
        const mod = (time * d.speed + d.phase) % 2
        const lin = mod < 1 ? mod : 2 - mod
        const a = 0.25 + 0.55 * lin

        if (a > 0.6) {
          ctx.shadowColor = dotGlow
          ctx.shadowBlur = 6 * ((a - 0.6) / 0.4)
        } else {
          ctx.shadowColor = 'transparent'
          ctx.shadowBlur = 0
        }
        ctx.globalAlpha = a * opacity
        ctx.beginPath()
        ctx.arc(d.x, d.y, radius, 0, Math.PI * 2)
        ctx.fill()
      }
      ctx.restore()
    }

    resize()
    build()

    if (reduce) {
      // One frame, at a fixed point in the cycle. Nothing is scheduled.
      paint(0.5)
      const ro = new ResizeObserver(() => { resize(); build(); paint(0.5) })
      ro.observe(wrap)
      return () => ro.disconnect()
    }

    const loop = (now) => {
      if (stopped) return
      if (visible) paint((now / 1000) * Math.max(speedScale, 0))
      raf = requestAnimationFrame(loop)
    }

    const ro = new ResizeObserver(() => { resize(); build() })
    ro.observe(wrap)

    // Stop painting while the section is off screen.
    const io = new IntersectionObserver(
      (entries) => { visible = entries[0]?.isIntersecting ?? true },
      { threshold: 0 },
    )
    io.observe(wrap)

    raf = requestAnimationFrame(loop)

    return () => {
      stopped = true
      cancelAnimationFrame(raf)
      ro.disconnect()
      io.disconnect()
    }
  }, [gap, radius, color, glowColor, colorVar, glowColorVar, opacity, backgroundOpacity, speedMin, speedMax, speedScale, reduce])

  return (
    <div ref={wrapRef} aria-hidden="true" className={className} style={{ position: 'absolute', inset: 0, ...style }}>
      <canvas ref={canvasRef} style={{ display: 'block', width: '100%', height: '100%' }} />
    </div>
  )
}
